# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibs" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "51f168e779af631aab75ceb779b82941c8378b8d12b3214ba4770f952294de4c"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "84cf79abcefd53c79fd1ebdaf7f94c1aca7a5ab7ede702f249c6848fcea1f0b1"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c06c72e2aabf0b739b2e5292568888a2f3e615c38a32ace8f5bd59eeb39eb69"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1f9826be731b7493182a8bd62070ac50bb7e0b8da5fe4e216bc2d96273dbbfe"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dibs"
  desc "Coordination and situational-awareness board for AI agents on one machine"
  homepage "https://github.com/agenxy/dibs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dibs"
  binary "dibd"
  manpage "dibs.1"

  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-dr", "com.apple.quarantine", staged_path.to_s],
                   must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    Start the daemon and point your agents at it:

      dibd &                  # 127.0.0.1:4777, data in ~/.dibs
      dibs mcp-config          # MCP config to add to your harness
      dibs admin set-password  # once, before `dibs web`
      dibs doctor              # what is quietly broken, and how to fix it

    Signed for provenance with cosign, but not notarised by Apple, so this
    cask clears the quarantine flag on install.
  EOS
end
