# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibs" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "58a57582ccb9b0ff4e378d3f4daaa1aa19b2bcb8fdd303a94a7dca215a251637"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fcbf6d7ceaf41af0ebdf7d998e261819918316072883d7350587b3210d88eb3a"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "331e67ddac1213d57ede097e5a3d65c062f9e2cf56e41c002b02b3ea66bf1f8e"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "017cda29d85faa893aa984fb4a5a0e95e90753e091499c82d9758f3434243bd5"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dibs"
  desc "Coordination and situational-awareness board for AI agents on one machine"
  homepage "https://github.com/agenxy/dibs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dibs"
  binary "dibd"
  manpage "dibs.1"

  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-dr", "com.apple.quarantine", staged_path.to_s],
                   must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    Start the daemon and point your agents at it:

      dibd &                  # 127.0.0.1:4777, data in ~/.dibs
      dibs mcp-config          # MCP config to add to your harness
      dibs admin set-password  # once, before `dibs web`
      dibs doctor              # what is quietly broken, and how to fix it

    Signed for provenance with cosign, but not notarised by Apple, so this
    cask clears the quarantine flag on install.
  EOS
end
