# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibs" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "26cb8f80dd0106481d13120731b630df89a945f7df36b99e96e2395bb5d2e43f"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "406719d4129ced54f72c86b90f8cca64af992208011baf297af9344beee75737"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1447472b1b3cd8b1f80f1091ed944f82b12209adccab69332e8d720ca4c74de4"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3bb03c8bd6bf4264c725250f8cbe73eb697be557fb011f22cdbf61c7d75819bb"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dibs"
  desc "Coordination and situational-awareness board for AI agents on one machine"
  homepage "https://github.com/agenxy/dibs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dibs"
  binary "dibd"
  manpage "dibs.1"

  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-dr", "com.apple.quarantine", staged_path.to_s],
                   must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    Start the daemon and point your agents at it:

      dibd &                  # 127.0.0.1:4777, data in ~/.dibs
      dibs mcp-config          # MCP config to add to your harness
      dibs admin set-password  # once, before `dibs web`
      dibs doctor              # what is quietly broken, and how to fix it

    Signed for provenance with cosign, but not notarised by Apple, so this
    cask clears the quarantine flag on install.
  EOS
end
