# This file was generated by GoReleaser. DO NOT EDIT.
cask "lanes" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "7fb4caf0f36543e742083bcf31d5be279d5a504ca9c9a61f4f61f81c4a0b8441"
      url "https://github.com/Agenxy/lanes/releases/download/v#{version}/lanes_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d23b2699aea9a38ea472cc400a1026d5b05e738712873328f49b1dd3ca8e411e"
      url "https://github.com/Agenxy/lanes/releases/download/v#{version}/lanes_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "857e5f02fbe3dcd1edbae626396c1afd3629263b9b029fe2857fcdb16c36560c"
      url "https://github.com/Agenxy/lanes/releases/download/v#{version}/lanes_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9129dce317677a6e16f82b166d15eb998a8312a3183663b4490340356fa51a68"
      url "https://github.com/Agenxy/lanes/releases/download/v#{version}/lanes_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lanes"
  desc "Coordination and situational-awareness board for AI agents on one machine"
  homepage "https://github.com/agenxy/lanes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lanes"
  binary "lanesd"
  manpage "lanes.1"

  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-dr", "com.apple.quarantine", staged_path.to_s],
                   must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    Start the daemon and point your agents at it:

      lanesd &                  # 127.0.0.1:4777, data in ~/.lanes
      lanes mcp-config          # MCP config to add to your harness
      lanes admin set-password  # once, before `lanes web`
      lanes doctor              # what is quietly broken, and how to fix it

    Signed for provenance with cosign, but not notarised by Apple, so this
    cask clears the quarantine flag on install.
  EOS
end
