# This file was generated by GoReleaser. DO NOT EDIT.
cask "lanes" do
  version "0.0.0"

  on_macos do
    on_intel do
      sha256 "63bef51458b6c653ac446af25ab93216ba0d477e05070c891a0d9f379d67edd4"
      url "https://github.com/Agenxy/lanes/releases/download/v#{version}/lanes_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b897a0f7b8900c03ca8b3c873afc52bd05d0153356cd09a1871eb5ca0c2ce933"
      url "https://github.com/Agenxy/lanes/releases/download/v#{version}/lanes_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e02b0ba647b9931ab214059de475e3e78eedab534c33df0246ca6e4a842a0f84"
      url "https://github.com/Agenxy/lanes/releases/download/v#{version}/lanes_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1ef82275a274b7886f13fe15a993d1abd62b8b6782c4f1704b00ff04089f781"
      url "https://github.com/Agenxy/lanes/releases/download/v#{version}/lanes_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lanes"
  desc "Coordination and situational-awareness board for AI agents on one machine"
  homepage "https://github.com/agenxy/lanes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lanes"
  binary "lanesd"

  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-dr", "com.apple.quarantine", staged_path.to_s],
                   must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    Start the daemon and point your agents at it:

      lanesd &                  # 127.0.0.1:4777, data in ~/.lanes
      lanes mcp-config          # MCP config to add to your harness
      lanes admin set-password  # once, before `lanes web`
      lanes doctor              # what is quietly broken, and how to fix it

    Signed for provenance with cosign, but not notarised by Apple, so this
    cask clears the quarantine flag on install.
  EOS
end
