# This file was generated by GoReleaser. DO NOT EDIT.
cask "lanes" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "31700b5741c3e67060c74d335ece35406f32b6d8dca27c2b78d959e8f51a4a6b"
      url "https://github.com/Agenxy/lanes/releases/download/v#{version}/lanes_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "159223265a95cb4e72eeeb5d6fec14f28796c59f018a2da23d15d6050e74436c"
      url "https://github.com/Agenxy/lanes/releases/download/v#{version}/lanes_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1d0f94146e4c6e7851188c5addc9071b868d639e0d367268a77186c8a8a6b84e"
      url "https://github.com/Agenxy/lanes/releases/download/v#{version}/lanes_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "414c1fccdf8de693ac947b2c31158916595ff8489846ff19badf7ef78d3fddfc"
      url "https://github.com/Agenxy/lanes/releases/download/v#{version}/lanes_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lanes"
  desc "Coordination and situational-awareness board for AI agents on one machine"
  homepage "https://github.com/agenxy/lanes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lanes"
  binary "lanesd"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}"],
                   must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    Start the daemon and point your agents at it:

      lanesd &                  # 127.0.0.1:4777, data in ~/.lanes
      lanes mcp-config          # MCP config to add to your harness
      lanes admin set-password  # once, before `lanes web`
      lanes doctor              # what is quietly broken, and how to fix it

    Signed for provenance with cosign, but not notarised by Apple, so this
    cask clears the quarantine flag on install.
  EOS
end
